import LegalPageLayout from './LegalPageLayout'

export default function Disclaimer() {
  return (
    <LegalPageLayout title="Disclaimer" lastUpdated="July 9, 2026">
      <section>
        <h2>Concept Tool, Not Licensed Design Services</h2>
        <p>
          My Everlasting Home is a pre-design inspiration tool. Every blueprint, floor zone list,
          material palette, and narrative it produces is a conceptual starting point generated from your
          quiz answers using AI models and deterministic design templates — it is not a substitute for
          work performed by a licensed architect, structural engineer, or other design professional.
        </p>
      </section>

      <section>
        <h2>No Construction Documents</h2>
        <p>
          Nothing generated by the Platform is a permit-ready construction document, structural
          calculation, or code-compliant plan. Square footage, room counts, budget ranges, and timelines
          shown are estimates for planning conversations only and will change once a licensed team
          evaluates your actual site, local codes, and requirements.
        </p>
      </section>

      <section>
        <h2>SCIP and Material Claims</h2>
        <p>
          References to SCIP (Structural Concrete Insulated Panel) construction and its performance
          characteristics — thermal mass, disaster resistance, longevity, and similar claims — are
          general, informational descriptions of the construction method and are not a guarantee of
          performance for any specific project. Actual performance depends on engineering, site
          conditions, and construction quality, and must be verified by qualified professionals.
        </p>
      </section>

      <section>
        <h2>AI-Generated Content</h2>
        <p>
          Portions of the Platform's output are generated using AI models. AI-generated text can be
          inaccurate, generic, or inconsistent with your actual inputs in edge cases. Review all generated
          content critically before relying on it.
        </p>
      </section>

      <section>
        <h2>No Professional Relationship</h2>
        <p>
          Using the Platform, including submitting your contact information to "connect with the EHBG
          team," does not by itself create a design, engineering, contracting, or other professional
          services relationship. Any such relationship begins only once a separate, explicit agreement is
          made.
        </p>
      </section>

      <section>
        <h2>Questions</h2>
        <p>
          If anything in a generated blueprint is unclear, reach out through our{' '}
          <a href="/contact">Contact page</a> before making any planning or purchasing decisions based on it.
        </p>
      </section>
    </LegalPageLayout>
  )
}
